### ISSUE TITLE
Creo que aún falta un igual en algún lado, porque no me deja escribir el saldo total para saldar la deuda.

### ISSUE THREAD

**Issue by SebastianMora98** [SebastianMora98/TallerElectivaII#15]
![image](https://user-images.githubusercontent.com/48461242/89079806-e91a1f80-d34c-11ea-8866-f7e89d69b87e.png)
 Creo que aún falta un igual en algún lado, porque no me deja escribir el saldo total para saldar la deuda.

_Originally posted by @KaiScary in https://github.com/SebastianMora98/TallerElectivaII/pull/14#issuecomment-667398495_

**Comment by KP-ctrl** [comment]
Arreglado!
